### ISSUE TITLE
MU100 missing wave info

### ISSUE THREAD

**Issue by 02FD** [shingo45endo/tone-browser#4]
I find this odd because the waves added for the MU100 are listed under "Waves" for the later MU models, but not the MU100 itself.

**Comment by shingo45endo** [comment]
Thank you for your report. After a brief investigation, it appears that the MU100 'extended' waveform data is stored separately from the 'basic' waveform data. However, the current implementation of [tone-para](https://github.com/shingo45endo/tone-para) only extracts the 'basic' waveform data. This will be corrected later.

**Comment by shingo45endo** [comment]
Fixed.
